name:                hw5
version:             0.1.0.0
github:              "githubuser/hw5"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hw5#readme>

dependencies:
- base >= 4.7 && < 5
- haskeline
- scientific
- mtl
- containers
- megaparsec
- parser-combinators
- text
- bytestring
- serialise
- zlib
- directory
- time
- random
- hspec
- transformers
# - text-format-simple
# - random-strings

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wincomplete-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - prettyprinter
    - prettyprinter-ansi-terminal

executables:
  hi:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw5
    - prettyprinter-ansi-terminal
    - prettyprinter

tests:
  hw5-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw5
